server:
  address: ":8080"

database:
  uri: "host=localhost user=postgres password=postgres dbname=hello port=5432 sslmode=disable"

sentry:
  dsn: "" # Add your Sentry DSN here
  environment: "development"

metrics:
  enabled: true
  path: "/metrics"

logger:
  level: "info" 
